export enum TyreCatVehicles {
    LEGRKOVOI_CAT_TYPE = 'легковий',
    LEGRKOVOI_CAT_TYPE_RU = 'легковой',
    VNEDOROGNIK_CAT_TYPE = 'позашляховик',
    VNEDOROGNIK_CAT_TYPE_RU = 'внедорожник',
    LEGKOGRUZ_CAT_TYPE = 'легковантажний',
    LEGKOGRUZ_CAT_TYPE_RU = 'легкогрузовой',
    SELHOZ_CAT_TYPE = 'с/г',
    SELHOZ_CAT_TYPE_RU = 'с/х',
    SPECTEHNIKA_CAT_TYPE = 'спецтехніка',
    SPECTEHNIKA_CAT_TYPE_RU = 'спецтехника',
    INDUSTRIALNA_CAT_TYPE = 'індустріальна',
    INDUSTRIALNA_CAT_TYPE_RU = 'индустриальная',
    CAREER_CAT_TYPE = "кар'єрна",
    CAREER_CAT_TYPE_RU = "карьерная",
    MOTO_CAT_TYPE = 'мото',
    BYCILE_CAT_TYPE = 'вело',
    TRUCK_CAT_TYPE = 'вантажні шини',
    TRUCK_CAT_TYPE_RU = 'грузовые шины',
};