export enum TyreType {
    LEGRKOVOI_TYPE = '/iconsTypeCar/londonCabClear64.webp',
    VNEDOROGNIK_TYPE = '/iconsTypeCar/pickup.webp',
    LEGKOGRUZ_TYPE = '/iconsTypeCar/van.webp',
    SELHOZ_TYPE = '/iconsTypeCar/tractor.webp',
    SPECTEHNIKA_TYPE = '/iconsTypeCar/bulldozer.webp',
    MOTO_TYPE = '/iconsTypeCar/scooter.webp',
    TRUCK_TYPE = '/iconsTypeCar/truck.webp',
    TRAILER_TRUCK_TYPE = '/iconsTypeCar/truck_trailer_64.webp',
    STEERING_TRUCK_TYPE = '/iconsTypeCar/truck_steer_64.webp',
    TRACKTION_TRUCK_TYPE = '/iconsTypeCar/truck_traction_64.webp',
    BICYCLE_TYPE = '/iconsTypeCar/bicycle_64.webp',
    INDUSTRIAL_TYPE = '/iconsTypeCar/asphalt_paver_64.webp',
    UNIVERSAL_TYPE = '/iconsTypeCar/truck_univer_60.webp',
    NO_TYPE = '/iconsTypeCar/noTypeCar.webp',
};