export enum TyreType {
    LEGRKOVOI_TYPE = '/iconsTypeCar/londonCabClear64.png',
    VNEDOROGNIK_TYPE = '/iconsTypeCar/pickup.png',
    LEGKOGRUZ_TYPE = '/iconsTypeCar/van.png',
    SELHOZ_TYPE = '/iconsTypeCar/tractor.png',
    SPECTEHNIKA_TYPE = '/iconsTypeCar/bulldozer.png',
    MOTO_TYPE = '/iconsTypeCar/scooter.png',
    TRUCK_TYPE = '/iconsTypeCar/truck.png',
    TRAILER_TRUCK_TYPE = '/iconsTypeCar/truck_trailer_64.png',
    STEERING_TRUCK_TYPE = '/iconsTypeCar/truck_steer_64.png',
    TRACKTION_TRUCK_TYPE = '/iconsTypeCar/truck_traction_64.png',
    BICYCLE_TYPE = '/iconsTypeCar/bicycle_64.png',
    INDUSTRIAL_TYPE = '/iconsTypeCar/asphalt_paver_64.png',
    UNIVERSAL_TYPE = '/iconsTypeCar/truck_univer_60.png',
    NO_TYPE = '/iconsTypeCar/noTypeCar.png',
};