export interface ItemPriceTyresConfigAttr {
  price_list_type: string;
  provider_id: number;
  provider: string;
  city: string;
  city_ua: string;
  id: number;
  id_goods_sup: number;
  brand_id: number;
  brand: string;
  model_id: number;
  model: string;
  country_manufacturer: string;
  country_manufacturer_ua: string;
  demo: string;
  diameter: string;
  height: string;
  homologation: string;
  load_index: string;
  load_index_with_desc: string;
  params: string;
  reinforce: string;
  run_flat: string;
  seal: string;
  season_id: number;
  season: string;
  season_ua: string;
  silent: string;
  size_only_digits: string;
  speed_index: string;
  speed_index_with_desc: string;
  studded: string;
  vehicle_type_id: number;
  vehicle_type: string;
  vehicle_type_ua: string;
  width: string;
  manufacture_year: string;
  full_name: string;
  photo_url: string;
  update_date: Date;
  in_stock: number;
  user_price_wholesale: number;
  user_price: number;
  user_delivery_price: number;
  user_price_plus_user_delivery_price: number;
  id_sup: number;

  ['Категория товара']: string;
  ['ID Постачальника']: number;
  ['Поставщик']: string;
  ['Город']: string;
  ['Город (укр)']: string;
  ['ID товара']: number;
  ['Артикул товару у постачальника']: number;
  ['ID Бренда']: number;
  ['Бренд']: string;
  ['ID Моделі']: number;
  ['Модель']: string;
  ['Страна производитель']: string;
  ['Страна производитель (укр)']: string;
  //demo: string;
  ['Диаметр']: string;
  ['Высота профиля']: string;
  ['Оммологация']: string;
  ['Индекс нагрузки']: string;
  ['Індекс навантаження з описом']: string;
  ['Параметры']: string;
  ['Усиление']: string;
  ['RunFlat']: string;
  //seal: string;
  ['ID Сезону']: number;
  ['Сезон']: string;
  ['Сезон (укр)']: string;
  //silent: string;
  ['ID розміру']: string;
  ['Индекс скорости']: string;
  ['Індекс швидкості з описом']: string;
  ['Шип/не шип']: string;
  ['ID типу транспортного засобу (призначення)']: number;
  ['Тип транспортного средства (назначение)']: string;
  ['Тип транспортного средства (назначение) (укр)']: string;
  ['Ширина профиля']: string;
  ['Год изготовления шин']: string;
  ['Полное название товара']: string;
  ['Посилання на фото']: string;
  ['Дата обновления']: Date;
  ['В наличии']: number;
  ['Моя оптовая цена (со скидкой)']: number;
  ['Моя розничная цена']: number;
  ['Моя ціна доставки']: number;
  ['Моя роздрібна ціна+доставка']: number;
  ['Артикул товару у постачальника']: number;
};
