import { PartialType } from '@nestjs/mapped-types';
import { CreateOrderDto } from './create-order.dto';

export class UpdateOrderDto extends PartialType(CreateOrderDto) {
  readonly id_tyre: number;
  readonly id_wheel: number;
  readonly id_oil: number;
  readonly id_battery: number;
  readonly price: number;
  readonly quantity: number;
  readonly total: number;
  readonly notes: string;
  readonly reserve: number;
  readonly status: string;
  readonly bonus: number;
  //readonly price_wholesale: number;
  readonly id_basket: number;
  readonly id_order_storage: number;
  //readonly delivery_price: number;
  //readonly price_plus_delivery: number;
  //readonly update_date: Date;
  readonly n: number;
  readonly id: number;
  readonly id_user: number;
  readonly id_supplier: number;
  readonly organisation: string;
  readonly order_view: string;
  readonly delivery: string;
  readonly status_delivery: string;
  readonly delivery_ttn: string;
  readonly pay_view: string;
  readonly status_pay: string;
  readonly id_customer: number;
  readonly id_contract: number;
  readonly category: string;
  //readonly full_name: string;
  readonly delivery_cost: number;
  readonly dop_garanty: number;
  readonly commission_cost: number;
  readonly bonus_decrease: number;
  readonly total_cost: number;
}
