import { TyreTypeNovaPoshta } from "./enum/TyresTypesNP.enum";

const tyresDiameter = (diameter: string | undefined) => {
    switch (diameter) {
        case '1':
            return TyreTypeNovaPoshta.REF_13_14;
        case '2':
            return TyreTypeNovaPoshta.REF_13_14;
        case '3':
            return TyreTypeNovaPoshta.REF_13_14;
        case '4':
            return TyreTypeNovaPoshta.REF_13_14;
        case '5':
            return TyreTypeNovaPoshta.REF_13_14;
        case '6':
            return TyreTypeNovaPoshta.REF_13_14;
        case '7':
            return TyreTypeNovaPoshta.REF_13_14;
        case '8':
            return TyreTypeNovaPoshta.REF_13_14;
        case '9':
            return TyreTypeNovaPoshta.REF_13_14;
        case '10':
            return TyreTypeNovaPoshta.REF_13_14;
        case '12':
            return TyreTypeNovaPoshta.REF_13_14;
        case '13':
            return TyreTypeNovaPoshta.REF_13_14;
        case '14':
            return TyreTypeNovaPoshta.REF_13_14;
        case '14.5':
            return TyreTypeNovaPoshta.REF_15_17;
        case '15':
            return TyreTypeNovaPoshta.REF_15_17;
        case '15.3':
            return TyreTypeNovaPoshta.REF_17_5;
        case '15.5':
            return TyreTypeNovaPoshta.REF_17_5;
        case '16':
            return TyreTypeNovaPoshta.REF_15_17;
        case '16.1':
            return TyreTypeNovaPoshta.REF_15_17;
        case '16.5':
            return TyreTypeNovaPoshta.REF_15_17;
        case '17':
            return TyreTypeNovaPoshta.REF_15_17;
        case '18':
            return TyreTypeNovaPoshta.REF_18_19;
        case '19':
            return TyreTypeNovaPoshta.REF_18_19;
        case '20':
            return TyreTypeNovaPoshta.REF_20_21;
        case '21':
            return TyreTypeNovaPoshta.REF_20_21;
        case '23':
            return TyreTypeNovaPoshta.REF_23;
        case '17.5':
            return TyreTypeNovaPoshta.REF_17_5;
        case '19.5':
            return TyreTypeNovaPoshta.REF_19_5;
        case '22.5':
            return TyreTypeNovaPoshta.REF_22_5;
        case '24':
            return TyreTypeNovaPoshta.REF_22_5;
        case '24.15':
            return TyreTypeNovaPoshta.REF_22_5;
        case '25':
            return TyreTypeNovaPoshta.REF_22_5;
        case '26':
            return TyreTypeNovaPoshta.REF_22_5;
        case '26.5':
            return TyreTypeNovaPoshta.REF_22_5;
        case '28':
            return TyreTypeNovaPoshta.REF_22_5;
        case '29':
            return TyreTypeNovaPoshta.REF_22_5;
        case '30':
            return TyreTypeNovaPoshta.REF_22_5;
        case '30.5':
            return TyreTypeNovaPoshta.REF_22_5;
        case '32':
            return TyreTypeNovaPoshta.REF_22_5;
        case '33':
            return TyreTypeNovaPoshta.REF_22_5;
        case '34':
            return TyreTypeNovaPoshta.REF_22_5;
        case '35':
            return TyreTypeNovaPoshta.REF_22_5;
        case '36':
            return TyreTypeNovaPoshta.REF_22_5;
        case '38':
            return TyreTypeNovaPoshta.REF_22_5;
        case '42':
            return TyreTypeNovaPoshta.REF_22_5;
        case '420':
            return TyreTypeNovaPoshta.REF_22_5;
        case '44':
            return TyreTypeNovaPoshta.REF_22_5;
        case '457':
            return TyreTypeNovaPoshta.REF_22_5;
        case '46':
            return TyreTypeNovaPoshta.REF_22_5;
        case '470':
            return TyreTypeNovaPoshta.REF_22_5;
        case '48':
            return TyreTypeNovaPoshta.REF_22_5;
        case '490':
            return TyreTypeNovaPoshta.REF_22_5;
        case '50':
            return TyreTypeNovaPoshta.REF_22_5;
        case '508':
            return TyreTypeNovaPoshta.REF_22_5;
        case '52':
            return TyreTypeNovaPoshta.REF_22_5;
        case '533':
            return TyreTypeNovaPoshta.REF_22_5;
        case '54':
            return TyreTypeNovaPoshta.REF_22_5;
        case '635':
            return TyreTypeNovaPoshta.REF_22_5;

    }
}

export {
    tyresDiameter
};