export type IDapertmentDelivery = {
    address?: string,
    id?: string,
    name?: string,
    operatingTime?: string,
    Phone?: string,
    EmailStorage?: string,
    latitude?: number,
    longitude?: number,
    latitudeCorrect?: number,
    longitudeCorrect?: number,
    Office?: boolean,
    CityId?: string,
    CityName?: string,
    IsWarehouse?: boolean,
    RcPhoneSecurity?: string,
    RcPhoneManagers?: string,
    RcPhone?: null,
    RcName?: boolean,
    WarehouseForDeliveryId?: string,
    IsCashOnDelivery?: boolean,
    WarehouseType?: number,
    CenterPickUpDelivery?: boolean
};